from __future__ import annotations

from storyos.multiply.prompt_loader import load_script_prompt
from storyos.multiply.source import StoryBundle, StorySource, as_bundle
from storyos.multiply.templates import FORMAT_LABELS

FORMAT_GUIDANCE = {
    "reel": "Write a 30–45 second Instagram Reel script in vertical format.",
    "shorts": "Write a 45–60 second YouTube Shorts script in 9:16 vertical format.",
    "youtube": "Write a 5–8 minute YouTube script with natural pacing and breathing room.",
}


def as_bundle(source: StoryBundle | StorySource) -> StoryBundle:
    if isinstance(source, StoryBundle):
        return source
    return StoryBundle(main=source)


def build_generation_prompt(
    source: StoryBundle | StorySource,
    fmt: str,
    *,
    script_prompt_path,
) -> str:
    bundle = as_bundle(source)
    main = bundle.main
    script_prompt = load_script_prompt(str(script_prompt_path))
    format_label = FORMAT_LABELS.get(fmt, fmt)
    format_guidance = FORMAT_GUIDANCE.get(fmt, "Write a cinematic script.")
    context_section = _format_context_section(bundle)

    return f"""{script_prompt}

---

## Task

Using ONLY the source material below, write a {format_label}.

{format_guidance}

Follow the Output Format from the script prompt exactly:
Story Discovery, Title, Hook, Full Script (cinematic scenes), Ending, Shot Suggestions, Music Direction.

Hard rules:
- Never invent experiences, events, dialogue, or details not supported by the source material.
- The **main story** drives the emotional arc: hook, transformation, and ending.
- **Background stories** supply context only — scenes, tension, B-roll, late-night details. Do not split into two main plots.
- Begin with a moment, not a lesson.
- Show before telling. Write scenes the camera can capture.
- Do not end with advice or "in conclusion".
- If the source is thin, build around the strongest moment — do not fabricate drama.

## Main story analysis (from StoryOS)

- Title: {main.title}
- Score: {main.candidate.score}/100
- Conflict: {main.candidate.conflict}
- Emotion: {main.candidate.emotion}
- Transformation: {main.candidate.transformation}
- Potential ending: {main.candidate.potential_ending}
- Categories: {", ".join(main.candidate.categories) if main.candidate.categories else "-"}

## Main story (emotional arc — do not go beyond this)

```text
{main.memory.content.strip()}
```
{context_section}
Write the final script in Markdown.
"""


def _format_context_section(bundle: StoryBundle) -> str:
    if not bundle.context:
        return ""

    blocks: list[str] = [
        "",
        "## Background context (supporting material only — not a second main story)",
        "",
    ]
    for item in bundle.context:
        blocks.append(f"### {item.title}")
        blocks.append("")
        blocks.append("```text")
        blocks.append(item.memory.content.strip())
        blocks.append("```")
        blocks.append("")
    return "\n".join(blocks)


def wrap_generated_script(
    body: str,
    *,
    source: StoryBundle | StorySource,
    fmt: str,
    provider: str,
    prompt_path,
) -> str:
    bundle = as_bundle(source)
    main = bundle.main
    context_note = ""
    if bundle.context:
        ids = ", ".join(bundle.context_story_ids())
        context_note = f"\n> Background stories: `{ids}`"

    return f"""# {main.title} — {FORMAT_LABELS.get(fmt, fmt)}

> Generated by StoryOS via `{provider}`  
> Script prompt: `{prompt_path}`  
> Main story: `{main.memory.id}` — edit before recording.{context_note}

---

{body.strip()}
"""
