from __future__ import annotations

from storyos.multiply.prompt_loader import load_script_prompt
from storyos.multiply.source import StoryBundle, StorySource
from storyos.multiply.templates import FORMAT_LABELS

FORMAT_GUIDANCE = {
    "reel": "Write a 30–45 second Instagram Reel script in vertical format.",
    "shorts": "Write a 45–60 second YouTube Shorts script in 9:16 vertical format.",
    "youtube": "Write a 5–8 minute YouTube script with natural pacing and breathing room.",
}


def build_generation_prompt(
    bundle: StoryBundle,
    fmt: str,
    *,
    script_prompt_path,
) -> str:
    source = bundle.main
    script_prompt = load_script_prompt(str(script_prompt_path))
    format_label = FORMAT_LABELS.get(fmt, fmt)
    format_guidance = FORMAT_GUIDANCE.get(fmt, "Write a cinematic script.")
    background_section = _background_section(bundle)

    return f"""{script_prompt}

---

## Task

Using ONLY the source material below, write a {format_label}.

{format_guidance}

Follow the Output Format from the script prompt exactly:
Story Discovery, Title, Hook, Full Script (cinematic scenes), Ending, Shot Suggestions, Music Direction.

Hard rules:
- Never invent experiences, events, dialogue, or details not supported by the source material.
- The **main story** drives the emotional arc (hook, transformation, ending).
- **Background stories** are context only — use them for scenes, tension, and B-roll, not a second plot.
- Begin with a moment, not a lesson.
- Show before telling. Write scenes the camera can capture.
- Do not end with advice or "in conclusion".
- If the source is thin, build around the strongest moment — do not fabricate drama.

## Main story (from StoryOS)

- Title: {source.title}
- Score: {source.candidate.score}/100
- Conflict: {source.candidate.conflict}
- Emotion: {source.candidate.emotion}
- Transformation: {source.candidate.transformation}
- Potential ending: {source.candidate.potential_ending}
- Categories: {", ".join(source.candidate.categories) if source.candidate.categories else "-"}

## Main story memory (author material — do not go beyond this)

```text
{source.memory.content.strip()}
```
{background_section}
Write the final script in Markdown.
"""


def wrap_generated_script(
    body: str,
    *,
    bundle: StoryBundle,
    fmt: str,
    provider: str,
    prompt_path,
) -> str:
    source = bundle.main
    context_note = ""
    if bundle.context:
        ids = ", ".join(item.candidate.short_id() for item in bundle.context)
        context_note = f"\n> Background stories: `{ids}`"

    return f"""# {source.title} — {FORMAT_LABELS.get(fmt, fmt)}

> Generated by StoryOS via `{provider}`  
> Script prompt: `{prompt_path}`  
> Main story: `{source.memory.id}` — edit before recording.{context_note}

---

{body.strip()}
"""


def _background_section(bundle: StoryBundle) -> str:
    if not bundle.context:
        return ""

    blocks: list[str] = []
    for index, item in enumerate(bundle.context, start=1):
        blocks.append(
            f"""### Background {index}: {item.title}

```text
{item.memory.content.strip()}
```"""
        )
    return "\n\n## Background stories (context only — do not make these the main arc)\n\n" + "\n\n".join(blocks) + "\n"
