from __future__ import annotations

from storyos.models.developed_story import DevelopedStory, SHAREABILITY_PRIVATE
from storyos.multiply.formats import PUBLIC_FORMATS
from storyos.multiply.prompt_loader import load_script_prompt, resolve_format_prompt
from storyos.multiply.source import StoryBundle, StorySource, as_bundle
from storyos.multiply.formats import FORMAT_GUIDANCE, FORMAT_LABELS


def build_generation_prompt(
    source: StoryBundle | StorySource,
    fmt: str,
    *,
    script_prompt_path,
    developed: DevelopedStory | None = None,
) -> str:
    bundle = as_bundle(source)
    main = bundle.main
    normalized = fmt.strip().lower()
    if normalized in {"journal", "linkedin", "blog", "newsletter", "podcast"}:
        script_prompt = resolve_format_prompt(normalized, script_prompt_path=script_prompt_path)
    else:
        script_prompt = load_script_prompt(str(script_prompt_path))
    format_label = FORMAT_LABELS.get(normalized, normalized)
    format_guidance = FORMAT_GUIDANCE.get(normalized, "Write in the creator's voice.")
    context_section = _format_context_section(bundle)
    interview_section = _format_interview_section(developed)

    return f"""{script_prompt}

---

## Task

Using ONLY the source material below, write a {format_label}.

{format_guidance}

Hard rules:
- Never invent experiences, events, dialogue, or details not supported by the source material.
- The **main story** drives the emotional arc: hook, transformation, and ending.
- **Background stories** supply context only — scenes, tension, B-roll, late-night details. Do not split into two main plots.
- **Interview answers** are the creator's own words — use them faithfully.
- Begin with a moment, not a lesson.
- Show before telling. Write scenes the camera can capture when the format is video.
- Do not end with advice or "in conclusion" unless the format requires a soft open ending.
- If the source is thin, build around the strongest moment — do not fabricate drama.

## Main story analysis (from StoryOS)

- Title: {main.title}
- Score: {main.candidate.score}/100
- Conflict: {main.candidate.conflict}
- Emotion: {main.candidate.emotion}
- Transformation: {main.candidate.transformation}
- Potential ending: {main.candidate.potential_ending}
- Categories: {", ".join(main.candidate.categories) if main.candidate.categories else "-"}

## Main story (emotional arc — do not go beyond this)

```text
{main.memory.content.strip()}
```
{context_section}{interview_section}
Write the final output in Markdown.
"""


def check_shareability(fmt: str, developed: DevelopedStory | None) -> None:
    normalized = fmt.strip().lower()
    if normalized not in PUBLIC_FORMATS:
        return
    if developed is None:
        return
    if developed.shareability == SHAREABILITY_PRIVATE:
        raise ValueError(
            f"Story {developed.short_id()} is marked private. "
            "Use journal format or update shareability before public outputs."
        )


def _format_context_section(bundle: StoryBundle) -> str:
    if not bundle.context:
        return ""

    blocks: list[str] = [
        "",
        "## Background context (supporting material only — not a second main story)",
        "",
    ]
    for item in bundle.context:
        blocks.append(f"### {item.title}")
        blocks.append("")
        blocks.append("```text")
        blocks.append(item.memory.content.strip())
        blocks.append("```")
        blocks.append("")
    return "\n".join(blocks)


def _format_interview_section(developed: DevelopedStory | None) -> str:
    if developed is None or not developed.narrative_text():
        return ""
    return f"""
## Creator interview (their words — do not rewrite)

```text
{developed.narrative_text()}
```
"""


def wrap_generated_script(
    body: str,
    *,
    source: StoryBundle | StorySource,
    fmt: str,
    provider: str,
    prompt_path,
    developed: DevelopedStory | None = None,
) -> str:
    bundle = as_bundle(source)
    main = bundle.main
    context_note = ""
    if bundle.context:
        ids = ", ".join(bundle.context_story_ids())
        context_note = f"\n> Background stories: `{ids}`"
    developed_note = ""
    if developed:
        developed_note = f"\n> Developed story: `{developed.short_id()}`"

    return f"""# {main.title} — {FORMAT_LABELS.get(fmt, fmt)}

> Generated by StoryOS via `{provider}`  
> Script prompt: `{prompt_path}`  
> Main story: `{main.memory.id}` — edit before recording.{context_note}{developed_note}

---

{body.strip()}
"""
