from __future__ import annotations

from unittest.mock import MagicMock, patch

from storyos.capture.manual import capture_from_text
from storyos.engine.analyzer import analyze_memory
from storyos.llm.config import LLMConfig, load_llm_config
from storyos.llm.registry import get_provider, resolve_provider_name
from storyos.multiply.generator import generate_script_content
from storyos.multiply.prompt_builder import build_generation_prompt
from storyos.multiply.source import build_story_bundle, build_story_source


SAMPLE = """\
topic: Production incident after hours
impact: Realized praise is not worth burnout.
blockers: The issue was not even ours, but I stayed up fixing it.
remember: Nobody asked me to sacrifice myself.
Got paged at 2AM and could not sleep afterwards.
"""


def _sample_source():
    memory = capture_from_text(SAMPLE, source="doclog")
    candidate = analyze_memory(memory)
    assert candidate is not None
    return build_story_source(candidate, memory)


def _sample_bundle():
    return build_story_bundle(_sample_source())


def test_build_generation_prompt_includes_source_only_rules(tmp_path) -> None:
    prompt_path = tmp_path / "storypromt.md"
    prompt_path.write_text("# Script rules\nNever invent experiences.", encoding="utf-8")
    bundle = _sample_bundle()
    prompt = build_generation_prompt(bundle, "reel", script_prompt_path=prompt_path)
    assert "Never invent experiences" in prompt
    assert "Nobody asked me to sacrifice myself" in prompt
    assert "Production incident after hours" in prompt


def test_resolve_provider_name_flags() -> None:
    assert resolve_provider_name(template=True) == "template"
    assert resolve_provider_name(prompt_only=True) == "prompt_only"
    assert resolve_provider_name("openai", config=LLMConfig(provider="cursor")) == "openai"


def test_generate_with_template_fallback(tmp_path) -> None:
    prompt_path = tmp_path / "storypromt.md"
    prompt_path.write_text("# rules", encoding="utf-8")
    bundle = _sample_bundle()
    result = generate_script_content(
        bundle,
        "reel",
        llm=LLMConfig(),
        script_prompt_path=prompt_path,
        use_template=True,
    )
    assert result.provider == "template"
    assert result.used_ai is False
    assert "## Story Discovery" in result.content


def test_generate_with_mock_cursor_provider(tmp_path) -> None:
    prompt_path = tmp_path / "storypromt.md"
    prompt_path.write_text("# rules", encoding="utf-8")
    bundle = _sample_bundle()
    provider = MagicMock()
    provider.is_available.return_value = True
    provider.generate.return_value = "## Hook\nA real moment.\n\n## Full Script\nScene one."

    with patch("storyos.multiply.generator.get_provider", return_value=provider):
        result = generate_script_content(
            bundle,
            "reel",
            llm=LLMConfig(provider="cursor"),
            script_prompt_path=prompt_path,
            provider_override="cursor",
        )

    assert result.used_ai is True
    assert result.provider == "cursor"
    assert "Generated by StoryOS via `cursor`" in result.content
    provider.generate.assert_called_once()
    assert "Nobody asked me to sacrifice myself" in provider.generate.call_args[0][0]


def test_cursor_provider_unavailable_raises() -> None:
    provider = get_provider("cursor", LLMConfig(cursor={"command": "missing-cursor-cli-xyz"}))
    assert not provider.is_available()


def test_load_llm_config_inherits_doclog_provider(monkeypatch, tmp_path) -> None:
    doclog_home = tmp_path / ".doclog"
    doclog_home.mkdir()
    (doclog_home / "config.yaml").write_text(
        "llm:\n  provider: copilot\ncopilot:\n  command: copilot\n",
        encoding="utf-8",
    )
    monkeypatch.setattr("storyos.llm.config.Path.home", lambda: tmp_path)
    config = load_llm_config({})
    assert config.provider == "copilot"
    assert config.copilot.get("command") == "copilot"
